footer_copyright: © 2026 Steff Dziadkowiec. All rights reserved.
social_intro_text: "Follow the journey:"
instagram_url: https://instagram.com/caelumnightwhisper
twitter_url: https://twitter.com/caelumnightwhisper
facebook_url: https://facebook.com/caelumnightwhisper
artstation_url: https://artstation.com/caelumnightwhisper
tumblr_url: https://cha-c-san.tumblr.com/
bluesky_url: https://bsky.app/profile/chacsan.bsky.social
